
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed execute;
	private global::Gtk.Label label1;
	private global::Gtk.FileChooserButton filechooserbutton;
	private global::Gtk.ScrolledWindow inputScrolledWindow;
	private global::Gtk.TextView input;
	private global::Gtk.ScrolledWindow statemenScrolledWindows;
	private global::Gtk.TreeView statements;
	private global::Gtk.ScrolledWindow variablesScrolledWindows;
	private global::Gtk.TreeView variables;
	private global::Gtk.Button exec;
	private global::Gtk.ScrolledWindow consoleScrolledWindow;
	private global::Gtk.TextView console;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 800;
		this.HeightRequest = 640;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.execute = new global::Gtk.Fixed ();
		this.execute.Name = "execute";
		this.execute.HasWindow = false;
		// Container child execute.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.HeightRequest = 25;
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Open File");
		this.execute.Add (this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.execute [this.label1]));
		w1.X = 20;
		w1.Y = 16;
		// Container child execute.Gtk.Fixed+FixedChild
		this.filechooserbutton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.filechooserbutton.WidthRequest = 175;
		this.filechooserbutton.Name = "filechooserbutton";
		this.execute.Add (this.filechooserbutton);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.execute [this.filechooserbutton]));
		w2.X = 75;
		w2.Y = 15;
		// Container child execute.Gtk.Fixed+FixedChild
		this.inputScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.inputScrolledWindow.WidthRequest = 240;
		this.inputScrolledWindow.HeightRequest = 240;
		this.inputScrolledWindow.Name = "inputScrolledWindow";
		this.inputScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child inputScrolledWindow.Gtk.Container+ContainerChild
		this.input = new global::Gtk.TextView ();
		this.input.CanFocus = true;
		this.input.Name = "input";
		this.inputScrolledWindow.Add (this.input);
		this.execute.Add (this.inputScrolledWindow);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.execute [this.inputScrolledWindow]));
		w4.X = 20;
		w4.Y = 69;
		// Container child execute.Gtk.Fixed+FixedChild
		this.statemenScrolledWindows = new global::Gtk.ScrolledWindow ();
		this.statemenScrolledWindows.WidthRequest = 240;
		this.statemenScrolledWindows.HeightRequest = 240;
		this.statemenScrolledWindows.Name = "statemenScrolledWindows";
		this.statemenScrolledWindows.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child statemenScrolledWindows.Gtk.Container+ContainerChild
		this.statements = new global::Gtk.TreeView ();
		this.statements.WidthRequest = 0;
		this.statements.CanFocus = true;
		this.statements.Name = "statements";
		this.statemenScrolledWindows.Add (this.statements);
		this.execute.Add (this.statemenScrolledWindows);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.execute [this.statemenScrolledWindows]));
		w6.X = 280;
		w6.Y = 68;
		// Container child execute.Gtk.Fixed+FixedChild
		this.variablesScrolledWindows = new global::Gtk.ScrolledWindow ();
		this.variablesScrolledWindows.WidthRequest = 240;
		this.variablesScrolledWindows.HeightRequest = 240;
		this.variablesScrolledWindows.Name = "variablesScrolledWindows";
		this.variablesScrolledWindows.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child variablesScrolledWindows.Gtk.Container+ContainerChild
		this.variables = new global::Gtk.TreeView ();
		this.variables.CanFocus = true;
		this.variables.Name = "variables";
		this.variablesScrolledWindows.Add (this.variables);
		this.execute.Add (this.variablesScrolledWindows);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.execute [this.variablesScrolledWindows]));
		w8.X = 540;
		w8.Y = 69;
		// Container child execute.Gtk.Fixed+FixedChild
		this.exec = new global::Gtk.Button ();
		this.exec.WidthRequest = 760;
		this.exec.HeightRequest = 35;
		this.exec.CanFocus = true;
		this.exec.Name = "exec";
		this.exec.UseUnderline = true;
		this.exec.Label = global::Mono.Unix.Catalog.GetString ("EXECUTE");
		this.execute.Add (this.exec);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.execute [this.exec]));
		w9.X = 20;
		w9.Y = 320;
		// Container child execute.Gtk.Fixed+FixedChild
		this.consoleScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.consoleScrolledWindow.WidthRequest = 760;
		this.consoleScrolledWindow.HeightRequest = 250;
		this.consoleScrolledWindow.Name = "consoleScrolledWindow";
		this.consoleScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child consoleScrolledWindow.Gtk.Container+ContainerChild
		this.console = new global::Gtk.TextView ();
		this.console.CanFocus = true;
		this.console.Name = "console";
		this.console.Editable = false;
		this.consoleScrolledWindow.Add (this.console);
		this.execute.Add (this.consoleScrolledWindow);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.execute [this.consoleScrolledWindow]));
		w11.X = 20;
		w11.Y = 370;
		this.Add (this.execute);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.exec.Clicked += new global::System.EventHandler (this.OnExecClicked);
	}
}
